version: '3.3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    volumes:
      - ./docker-data/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
